### ISSUE TITLE
Cannot start zcash bitcore

### ISSUE THREAD

**Issue by karelbilek** [str4d/insight-ui-zcash#3]
I am trying to run zcash bitcore and I keep getting this error

> [2016-11-02T09:03:22.831Z] info: Using config: /home/karel/.bitcore/zcash-bitcore-node.json
> [2016-11-02T09:03:22.833Z] info: Using network: livenet
> [2016-11-02T09:03:22.834Z] info: Starting bitcoind
> [2016-11-02T09:03:22.837Z] info: Using zcash config file: /home/karel/.bitcore/data/zcash.conf
> [2016-11-02T09:03:22.843Z] info: Starting zcash process
> execvp(): No such file or directory
> [2016-11-02T09:03:22.860Z] error: Error: spawn ENOENT
>     at errnoException (child_process.js:988:11)
>     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
> [2016-11-02T09:03:23.126Z] info: Zcash Height: 745 Percentage: 100.00
> [2016-11-02T09:03:23.136Z] info: Zcash Daemon Ready
> [2016-11-02T09:03:23.139Z] info: Starting web
> [2016-11-02T09:03:23.255Z] info: Bitcore Node ready
> [2016-11-02T09:03:23.601Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:23.602Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:23.602Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:23.602Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:24.103Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:24.104Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2016-11-02T09:03:24.104Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332

I am not sure *which* file is missing ("no such file or directory"). I have zcash daemon running already. Both `/home/karel/.bitcore/data/zcash.conf` and `/home/karel/.bitcore/data/zcash.conf` exist.

**Comment by karelbilek** [comment]
Oh, it's the exec in `/home/karel/.bitcore/zcash-bitcore-node.json` that doesn't exist.

**Comment by karelbilek** [comment]
I had to install zcashd from deb package (since the build never finished). I think now it might be working right.
